# yaml 
version: "3"
services:
  web:
    # build: .
    image: ghcr.io/3kmfi6hp/argo-airport-paas:main
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/"]
      interval: 30s
      timeout: 30s
      retries: 3
    # ports:
    #   - "80:3000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    # networks:
    #   - webnet
  web-2:
    # build: .
    image: ghcr.io/3kmfi6hp/argo-airport-paas:main
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000/"]
      interval: 30s
      timeout: 30s
      retries: 3
    # ports:
    #   - "86:3000"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
#     networks:
#       - webnet
# networks:
#   webnet:  
